(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Group_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(204,104,117,0.8)").s().p("AgCCEQgLgEgGgDIgbgTQgPgKgMgJQgPgMgHgNQgPgVgJgbQgNgtAXgoQAUglAogRQgXALgRAUQgSAVgHAZQgGAZAEAYQAFAZAOASIAAAAIAUAbIgJgOIgGgIQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBgBAAQgOgXgDgcQgDgcAKgaQAKgaAUgTQAVgTAagGIANgEIAJACQAFADABgBQAZgCAZALQASAHAXAQIACAHQAYAfgBAlQAAgRgHgSQgIgVgRgQQgQgPgXgHQgXgGgWADIgSADIgPAFIgOAFQgFACADgFIACgDQgNAIgLATIgEACIgDAGQgIACgFAMQAAgEgBgCIAAAJIgDAMIgCAUQgCACgBAEQgBAEABADIACAJQABAIAFAQQABAPALAJIADADIABAGQAEAGAMAFQAKAPAMAKQABAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAIgCgGIAIADIAHAAIAMgCIAMACQAFABAGAAIALAEIAJgCQAEACADAAIAIgEIAJABIAIgFQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQABgCAGgDIAIgFIAMgGIABgCIAIgGIAEgFIALgNIgCAJIgEAKQABABAEgEIAIgHQgEAHABADIADADQABADgKAPQgTAegYAMQgCACgKAAIgRACIgMAFQgGADgGAAIgDAAQgJAAgKgCg");
	this.shape.setTransform(12.4,13.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(213,130,141,0.698)").s().p("AgeBYQgOgSgFgYQgEgaAGgYQAHgZASgUQARgVAWgLIAOgEIAOgDIAGgBIgNAEQgaAGgUAUQgUASgKAbQgKAZADAcQADAcAOAXg");
	this.shape_1.setTransform(5.7,9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D5828D").s().p("AgCAMQgMgKgLgOIAFADIABAEQATAKAaABIgMACIgHAAIgIgDIABAGQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgCgBg");
	this.shape_2.setTransform(8.9,20.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(208,114,126,0.8)").s().p("AgGAXIgBgoQAAgDADgCQADgCABADIACARIAGgIIgEAGIAAAKQgCAIgEAHIgEAFIAAgBg");
	this.shape_3.setTransform(25.8,14.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_1, new cjs.Rectangle(0,0,26.7,26.9), null);


(lib.Group_0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(204,104,117,0.8)").s().p("AhNB4QgogWgTgrQAMAZAWATQAXATAbAHQAbAIAbgFQAbgFAUgPQARgMAMgKQgEABgKAJIgJAHQABgBAAAAQAAgBAAABQgBAAgBABQgBABgCABQgaAQgdADQgfADgcgKQgegMgTgVQgVgXgIgdIgEgOIACgKQADgFgBgCQgCgaALgdQAKgUAQgYIAIgDQAmgfAuAFQgYgCgYAKQgYAJgRATQgSAUgHAXQgHAXAEAZIADAWQADALAJAVQACAFgFgDIgEgDQAKAPAUANIACAEIAHADQAAADAFAFQAFAEAGACQgEgBgDACQAFgBAFABIANADIAWADQAIAGAGgDIAKgCQAJgBASgFQARgCAJgMIAFgDIAFgBQAHgFAGgMQASgNAJgNQAAgBABAAQAAgBAAAAQAAgBgBAAQAAAAgBAAQgCAAgDACIACgJIAAgIIgBgNIACgNIACgNQAAgGAEgGIgDgKQACgCAAgGIgBgDIgEgGIABgJIgFgKIACgBIgGgHQgCgFgEgEIgGgNIgCgBIgHgJIgMgLIgIgFIAKADIAKAEQACgBgFgFIgIgIQAIAFADgBIAEgDQACgBARALQAgAWAMAZQACACABAKQABAOACAFIAEAMQADAHABAHQAAAKgDAOQgDAMgEAGIgJAOIgLAPIgUAeQgNAQgPAIQgVARgfAJQgQAFgQAAQgfAAgegQg");
	this.shape.setTransform(14.6,15.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(213,130,141,0.698)").s().p("AgEAzQgbgGgXgUQgWgSgMgZIgJgdIgBgIIAFAOQAIAdAVAWQASAVAfAMQAbALAfgEQAegDAagPIgCACQgUAPgbAFQgLACgLAAQgRAAgPgFg");
	this.shape_1.setTransform(9.9,22.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D5828D").s().p("AgKAXIAFgCQALgUACgdIABANIAAAIIgCAJQADgCACAAQABAAAAAAQABAAAAAAQAAABAAAAQgBABAAABQgJAMgRAOg");
	this.shape_2.setTransform(23,19.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(208,114,126,0.8)").s().p("AAGAGIgYAAQgDAAgCgDQgDgDAEgBIAMgBQAGAAABgBIgDgCIALAAQANADAIAIIgMAAIgIAAg");
	this.shape_3.setTransform(15.5,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_0, new cjs.Rectangle(0,0.4,29.2,28.6), null);


(lib.Group = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(204,104,117,0.8)").s().p("AhHCRQgCACgDAAQgDABgRgMQgigXgOgdQgCgCgBgLIgDgUIgFgOQgDgIAAgGQgBgKADgQQAEgNAEgHIAUghQAIgMAPgUQAPgSAPgJQAZgSAggKQA1gOAxAaQAsAXAVAwQgOgcgYgUQgZgVgegIQgdgIgeAGQgdAFgWAQIgJAGIgIAGIgQAMIAQgLIAKgIIAEgDQAdgRAggDQAigDAfALQAgAMAWAYQAXAZAJAgIACAGIADAKQAAAEgDAGQgCAGABACQACAdgMAgQgKAXgTAbIgIADQgkAdgsABQAUgBAUgIQAbgLATgVQATgVAIgbQAIgbgEgbIgEgZQgBgGgFgMIgHgQQgDgHAGAEIAEADQgKgPgXgQIgCgEIgIgDQgBgEgFgFQgEgDgIgEQAFABACgCIgKAAIgPgEIgYgDQgDgCgFgBQgFgCgDACIgLACQgNABgRAGQgSACgMANIgEADIgGABQgIAHgHAMQgSAOgLAPQgBABAAABQAAABAAAAQAAABAAAAQAAAAABAAQADAAADgDIgDALIAAAIIAAAPIgCAOQgCAJABAGQgCAJgCAEIADALQgDAEAAAFIAGAKIgBALIAGAKQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAgBQACACAEAHIAHAJIAHAPIACABIAIAJIAOAMIAJAGIgLgDIgMgFQgBABAFAFIAJAIQgJgEgCABg");
	this.shape.setTransform(16,14.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(213,130,141,0.698)").s().p("ABqAzIgCgFQgJghgXgXQgWgZgggLQgegMgiAEQghADgdARIADgDQAWgQAdgFQAfgFAcAIQAeAHAZAVQAYAVAOAaIAGARIAEAQIABAIg");
	this.shape_1.setTransform(21.1,6.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D5828D").s().p("AgKARIAAgIIADgKQgDACgDAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBABgBQALgPARgOIgEAGIgFACQgNAXgDAgIAAgPg");
	this.shape_2.setTransform(6.5,10.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(208,114,126,0.8)").s().p("AAIAEIgMAAQgKgCgIgEQgJgGAEABQAJgBAoACQADAAADADQACADgDABIgNABQgIAAgBABIALAFg");
	this.shape_3.setTransform(14.8,30.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group, new cjs.Rectangle(0.1,0,31.9,31.7), null);


(lib.Group_1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(100,183,129,0.8)").s().p("AgCCEQgLgEgGgDIgbgTQgPgKgMgJQgPgMgHgNQgPgVgJgbQgNgtAXgoQAUglAogRQgXALgRAUQgSAVgHAZQgGAZAEAYQAFAZAOASIAAAAIAUAbIgJgOIgGgIQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBgBAAQgOgXgDgcQgDgcAKgaQAKgaAUgTQAVgTAagGIANgEIAJACQAFADABgBQAZgCAZALQASAHAXAQIACAHQAYAfgBAlQAAgRgHgSQgIgVgRgQQgQgPgXgHQgXgGgWADIgSADIgPAFIgOAFQgFACADgFIACgDQgNAIgLATIgEACIgDAGQgIACgFAMQAAgEgBgCIAAAJIgDAMIgCAUQgCACgBAEQgBAEABADIACAJQABAIAFAQQABAPALAJIADADIABAGQAEAGAMAFQAKAPAMAKQABAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAIgCgGIAIADIAHAAIAMgCIAMACQAFABAGAAIALAEIAJgCQAEACADAAIAIgEIAJABIAIgFQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQABgCAGgDIAIgFIAMgGIABgCIAIgGIAEgFIALgNIgCAJIgEAKQABABAEgEIAIgHQgEAHABADIADADQABADgKAPQgTAegYAMQgCACgKAAIgRACIgMAFQgGADgGAAIgDAAQgJAAgKgCg");
	this.shape_4.setTransform(12.4,13.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(126,197,151,0.698)").s().p("AgeBYQgOgSgFgYQgEgaAGgYQAHgZASgUQARgVAWgLIAOgEIAOgDIAGgBIgNAEQgaAGgUAUQgUASgKAbQgKAZADAcQADAcAOAXg");
	this.shape_5.setTransform(5.7,9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#7EC597").s().p("AgCAMQgMgKgLgOIAFADIABAEQATAKAaABIgMACIgHAAIgIgDIABAGQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgCgBg");
	this.shape_6.setTransform(8.9,20.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(109,188,137,0.8)").s().p("AgGAXIgBgoQAAgDADgCQADgCABADIACARIAGgIIgEAGIAAAKQgCAIgEAHIgEAFIAAgBg");
	this.shape_7.setTransform(25.8,14.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_1_1, new cjs.Rectangle(0,0,26.7,26.9), null);


(lib.Group_0_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(100,183,129,0.8)").s().p("AhNB4QgogWgTgrQAMAZAWATQAXATAbAHQAbAIAbgFQAbgFAUgPQARgMAMgKQgEABgKAJIgJAHQABgBAAAAQAAgBAAABQgBAAgBABQgBABgCABQgaAQgdADQgfADgcgKQgegMgTgVQgVgXgIgdIgEgOIACgKQADgFgBgCQgCgaALgdQAKgUAQgYIAIgDQAmgfAuAFQgYgCgYAKQgYAJgRATQgSAUgHAXQgHAXAEAZIADAWQADALAJAVQACAFgFgDIgEgDQAKAPAUANIACAEIAHADQAAADAFAFQAFAEAGACQgEgBgDACQAFgBAFABIANADIAWADQAIAGAGgDIAKgCQAJgBASgFQARgCAJgMIAFgDIAFgBQAHgFAGgMQASgNAJgNQAAgBABAAQAAgBAAAAQAAgBgBAAQAAAAgBAAQgCAAgDACIACgJIAAgIIgBgNIACgNIACgNQAAgGAEgGIgDgKQACgCAAgGIgBgDIgEgGIABgJIgFgKIACgBIgGgHQgCgFgEgEIgGgNIgCgBIgHgJIgMgLIgIgFIAKADIAKAEQACgBgFgFIgIgIQAIAFADgBIAEgDQACgBARALQAgAWAMAZQACACABAKQABAOACAFIAEAMQADAHABAHQAAAKgDAOQgDAMgEAGIgJAOIgLAPIgUAeQgNAQgPAIQgVARgfAJQgQAFgQAAQgfAAgegQg");
	this.shape_4.setTransform(14.6,15.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(126,197,151,0.698)").s().p("AgEAzQgbgGgXgUQgWgSgMgZIgJgdIgBgIIAFAOQAIAdAVAWQASAVAfAMQAbALAfgEQAegDAagPIgCACQgUAPgbAFQgLACgLAAQgRAAgPgFg");
	this.shape_5.setTransform(9.9,22.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#7EC597").s().p("AgKAXIAFgCQALgUACgdIABANIAAAIIgCAJQADgCACAAQABAAAAAAQABAAAAAAQAAABAAAAQgBABAAABQgJAMgRAOg");
	this.shape_6.setTransform(23,19.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(109,188,137,0.8)").s().p("AAGAGIgYAAQgDAAgCgDQgDgDAEgBIAMgBQAGAAABgBIgDgCIALAAQANADAIAIIgMAAIgIAAg");
	this.shape_7.setTransform(15.5,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_0_1, new cjs.Rectangle(0,0.4,29.2,28.6), null);


(lib.Group_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(100,183,129,0.8)").s().p("AhHCRQgCACgDAAQgDABgRgMQgigXgOgdQgCgCgBgLIgDgUIgFgOQgDgIAAgGQgBgKADgQQAEgNAEgHIAUghQAIgMAPgUQAPgSAPgJQAZgSAggKQA1gOAxAaQAsAXAVAwQgOgcgYgUQgZgVgegIQgdgIgeAGQgdAFgWAQIgJAGIgIAGIgQAMIAQgLIAKgIIAEgDQAdgRAggDQAigDAfALQAgAMAWAYQAXAZAJAgIACAGIADAKQAAAEgDAGQgCAGABACQACAdgMAgQgKAXgTAbIgIADQgkAdgsABQAUgBAUgIQAbgLATgVQATgVAIgbQAIgbgEgbIgEgZQgBgGgFgMIgHgQQgDgHAGAEIAEADQgKgPgXgQIgCgEIgIgDQgBgEgFgFQgEgDgIgEQAFABACgCIgKAAIgPgEIgYgDQgDgCgFgBQgFgCgDACIgLACQgNABgRAGQgSACgMANIgEADIgGABQgIAHgHAMQgSAOgLAPQgBABAAABQAAABAAAAQAAABAAAAQAAAAABAAQADAAADgDIgDALIAAAIIAAAPIgCAOQgCAJABAGQgCAJgCAEIADALQgDAEAAAFIAGAKIgBALIAGAKQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAgBQACACAEAHIAHAJIAHAPIACABIAIAJIAOAMIAJAGIgLgDIgMgFQgBABAFAFIAJAIQgJgEgCABg");
	this.shape_4.setTransform(16,14.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(126,197,151,0.698)").s().p("ABqAzIgCgFQgJghgXgXQgWgZgggLQgegMgiAEQghADgdARIADgDQAWgQAdgFQAfgFAcAIQAeAHAZAVQAYAVAOAaIAGARIAEAQIABAIg");
	this.shape_5.setTransform(21.1,6.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#7EC597").s().p("AgKARIAAgIIADgKQgDACgDAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBABgBQALgPARgOIgEAGIgFACQgNAXgDAgIAAgPg");
	this.shape_6.setTransform(6.5,10.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(109,188,137,0.8)").s().p("AAIAEIgMAAQgKgCgIgEQgJgGAEABQAJgBAoACQADAAADADQACADgDABIgNABQgIAAgBABIALAFg");
	this.shape_7.setTransform(14.8,30.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_2, new cjs.Rectangle(0.1,0,31.9,31.7), null);


(lib.Group_1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(109,162,210,0.8)").s().p("AgCCEQgLgEgGgDIgbgTQgPgKgMgJQgPgMgHgNQgPgVgJgbQgNgtAXgoQAUglAogRQgXALgRAUQgSAVgHAZQgGAZAEAYQAFAZAOASIAAAAIAUAbIgJgOIgGgIQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBgBAAQgOgXgDgcQgDgcAKgaQAKgaAUgTQAVgTAagGIANgEIAJACQAFADABgBQAZgCAZALQASAHAXAQIACAHQAYAfgBAlQAAgRgHgSQgIgVgRgQQgQgPgXgHQgXgGgWADIgSADIgPAFIgOAFQgFACADgFIACgDQgNAIgLATIgEACIgDAGQgIACgFAMQAAgEgBgCIAAAJIgDAMIgCAUQgCACgBAEQgBAEABADIACAJQABAIAFAQQABAPALAJIADADIABAGQAEAGAMAFQAKAPAMAKQABAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAIgCgGIAIADIAHAAIAMgCIAMACQAFABAGAAIALAEIAJgCQAEACADAAIAIgEIAJABIAIgFQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQABgCAGgDIAIgFIAMgGIABgCIAIgGIAEgFIALgNIgCAJIgEAKQABABAEgEIAIgHQgEAHABADIADADQABADgKAPQgTAegYAMQgCACgKAAIgRACIgMAFQgGADgGAAIgDAAQgJAAgKgCg");
	this.shape_8.setTransform(12.4,13.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(135,178,218,0.698)").s().p("AgeBYQgOgSgFgYQgEgaAGgYQAHgZASgUQARgVAWgLIAOgEIAOgDIAGgBIgNAEQgaAGgUAUQgUASgKAbQgKAZADAcQADAcAOAXg");
	this.shape_9.setTransform(5.7,9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#87B2DA").s().p("AgCAMQgMgKgLgOIAFADIABAEQATAKAaABIgMACIgHAAIgIgDIABAGQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgCgBg");
	this.shape_10.setTransform(8.9,20.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(118,167,213,0.8)").s().p("AgGAXIgBgoQAAgDADgCQADgCABADIACARIAGgIIgEAGIAAAKQgCAIgEAHIgEAFIAAgBg");
	this.shape_11.setTransform(25.8,14.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_1_2, new cjs.Rectangle(0,0,26.7,26.9), null);


(lib.Group_0_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(109,162,210,0.8)").s().p("AhNB4QgogWgTgrQAMAZAWATQAXATAbAHQAbAIAbgFQAbgFAUgPQARgMAMgKQgEABgKAJIgJAHQABgBAAAAQAAgBAAABQgBAAgBABQgBABgCABQgaAQgdADQgfADgcgKQgegMgTgVQgVgXgIgdIgEgOIACgKQADgFgBgCQgCgaALgdQAKgUAQgYIAIgDQAmgfAuAFQgYgCgYAKQgYAJgRATQgSAUgHAXQgHAXAEAZIADAWQADALAJAVQACAFgFgDIgEgDQAKAPAUANIACAEIAHADQAAADAFAFQAFAEAGACQgEgBgDACQAFgBAFABIANADIAWADQAIAGAGgDIAKgCQAJgBASgFQARgCAJgMIAFgDIAFgBQAHgFAGgMQASgNAJgNQAAgBABAAQAAgBAAAAQAAgBgBAAQAAAAgBAAQgCAAgDACIACgJIAAgIIgBgNIACgNIACgNQAAgGAEgGIgDgKQACgCAAgGIgBgDIgEgGIABgJIgFgKIACgBIgGgHQgCgFgEgEIgGgNIgCgBIgHgJIgMgLIgIgFIAKADIAKAEQACgBgFgFIgIgIQAIAFADgBIAEgDQACgBARALQAgAWAMAZQACACABAKQABAOACAFIAEAMQADAHABAHQAAAKgDAOQgDAMgEAGIgJAOIgLAPIgUAeQgNAQgPAIQgVARgfAJQgQAFgQAAQgfAAgegQg");
	this.shape_8.setTransform(14.6,15.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(135,178,218,0.698)").s().p("AgEAzQgbgGgXgUQgWgSgMgZIgJgdIgBgIIAFAOQAIAdAVAWQASAVAfAMQAbALAfgEQAegDAagPIgCACQgUAPgbAFQgLACgLAAQgRAAgPgFg");
	this.shape_9.setTransform(9.9,22.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#87B2DA").s().p("AgKAXIAFgCQALgUACgdIABANIAAAIIgCAJQADgCACAAQABAAAAAAQABAAAAAAQAAABAAAAQgBABAAABQgJAMgRAOg");
	this.shape_10.setTransform(23,19.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(118,167,213,0.8)").s().p("AAGAGIgYAAQgDAAgCgDQgDgDAEgBIAMgBQAGAAABgBIgDgCIALAAQANADAIAIIgMAAIgIAAg");
	this.shape_11.setTransform(15.5,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_0_2, new cjs.Rectangle(0,0.4,29.2,28.6), null);


(lib.Group_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(109,162,210,0.8)").s().p("AhHCRQgCACgDAAQgDABgRgMQgigXgOgdQgCgCgBgLIgDgUIgFgOQgDgIAAgGQgBgKADgQQAEgNAEgHIAUghQAIgMAPgUQAPgSAPgJQAZgSAggKQA1gOAxAaQAsAXAVAwQgOgcgYgUQgZgVgegIQgdgIgeAGQgdAFgWAQIgJAGIgIAGIgQAMIAQgLIAKgIIAEgDQAdgRAggDQAigDAfALQAgAMAWAYQAXAZAJAgIACAGIADAKQAAAEgDAGQgCAGABACQACAdgMAgQgKAXgTAbIgIADQgkAdgsABQAUgBAUgIQAbgLATgVQATgVAIgbQAIgbgEgbIgEgZQgBgGgFgMIgHgQQgDgHAGAEIAEADQgKgPgXgQIgCgEIgIgDQgBgEgFgFQgEgDgIgEQAFABACgCIgKAAIgPgEIgYgDQgDgCgFgBQgFgCgDACIgLACQgNABgRAGQgSACgMANIgEADIgGABQgIAHgHAMQgSAOgLAPQgBABAAABQAAABAAAAQAAABAAAAQAAAAABAAQADAAADgDIgDALIAAAIIAAAPIgCAOQgCAJABAGQgCAJgCAEIADALQgDAEAAAFIAGAKIgBALIAGAKQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAgBQACACAEAHIAHAJIAHAPIACABIAIAJIAOAMIAJAGIgLgDIgMgFQgBABAFAFIAJAIQgJgEgCABg");
	this.shape_8.setTransform(16,14.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(135,178,218,0.698)").s().p("ABqAzIgCgFQgJghgXgXQgWgZgggLQgegMgiAEQghADgdARIADgDQAWgQAdgFQAfgFAcAIQAeAHAZAVQAYAVAOAaIAGARIAEAQIABAIg");
	this.shape_9.setTransform(21.1,6.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#87B2DA").s().p("AgKARIAAgIIADgKQgDACgDAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBABgBQALgPARgOIgEAGIgFACQgNAXgDAgIAAgPg");
	this.shape_10.setTransform(6.5,10.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(118,167,213,0.8)").s().p("AAIAEIgMAAQgKgCgIgEQgJgGAEABQAJgBAoACQADAAADADQACADgDABIgNABQgIAAgBABIALAFg");
	this.shape_11.setTransform(14.8,30.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_3, new cjs.Rectangle(0.1,0,31.9,31.7), null);


(lib.ArtOnPathBrush_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Group_1();
	this.instance.parent = this;
	this.instance.setTransform(13.2,13.9,1,1,0,0,0,13.2,13.4);
	this.instance.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_1, new cjs.Rectangle(0,0.5,26.7,26.9), null);


(lib.ArtOnPathBrush_0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Group_0();
	this.instance.parent = this;
	this.instance.setTransform(15.2,14.7,1,1,0,0,0,14.6,14.7);
	this.instance.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_0, new cjs.Rectangle(0.6,0.4,29.2,28.6), null);


(lib.ArtOnPathBrush = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Group();
	this.instance.parent = this;
	this.instance.setTransform(16,15.8,1,1,0,0,0,16,15.8);
	this.instance.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush, new cjs.Rectangle(0.1,0,31.9,31.7), null);


(lib.redai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.ArtOnPathBrush_1();
	this.instance.parent = this;
	this.instance.setTransform(29.9,19.5,1,1,0,0,0,13.2,13.9);

	this.instance_1 = new lib.ArtOnPathBrush_0();
	this.instance_1.parent = this;
	this.instance_1.setTransform(31.9,18.7,1,1,0,0,0,15.2,14.7);

	this.instance_2 = new lib.ArtOnPathBrush();
	this.instance_2.parent = this;
	this.instance_2.setTransform(28.9,17.6,1,1,0,0,0,16,15.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B32538").s().p("AgUCxIgQgDQgJgBgFgDIgBAAQABgBgKgDQgKgCgBgCQgEgDgFgBIgJgDQgBgEgFgCQgKgDgCgCIgOgOIAAACIgOgPIgMgQQgMgTgEgPQABABAAAAQABABAAAAQAAgBgBAAQgBgBgBgBIgCgIIgBAAIgEgHQgDgEABgEQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAQgEgJAAgGIAAgsIAAACIABgGIgCABQABgBAAgGQABgGABABIAAABQACABACgKIgCABIABgEIAGgQQACgGAFgGIAAgEQAFgHAFgKQAGgLAGgDIAQgSQAFgHAMgKIANgIQAIgEAEAAIAQgHIAOgGQAAABAAAAQAAAAABAAQAAABABAAQABgBABAAQAGgCABABQAAgBAAAAQAAAAAAgBQABAAABAAQAAAAABAAQAFgBABgBIAAACIASgCIgCABQAAABAGgBIADgCIgBACIADgBIAAABQAIABAAgDIADACQAAAAABAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAEABQACABAEAAIgDAAIAFABQADABADgBIABgCIgFAAIAJgBIAAABIAFABQABABAAAAQABAAAAAAQABAAAAAAQAAAAABgBIAAACIAEAAQgEACAGACIAFACIgBgDIADADQABABAAAAQABAAAAAAQABAAABAAQAAAAABAAIgBACQABAAAAABQABAAAAAAQABAAAAAAQAAgBABAAIACABIgCAAIAPAFQAIADAEAEIAAABQAFAEAFACIgBgBIAHAEIgBACIAFADIgBAAQAHAHAFACIgBgBIAGgBIADACQABAAAAAAQAAAAABABQAAAAAAAAQABABAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAEADAEACQAAAAgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAACACAEIAIAIQADADACAEIAAAFQAAAAAAABQABAAAAABQABAAAAAAQABABAAAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIADAEQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAABIAAAAIAAABQABAEADAEIADAEQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIAAAEIADABIACAOIACARQgBABACAIIABgCIAAATIgBARIABADIgBAAIgCADIgBAQIgBgBIADgdIgCAAIgCAHIACACIgDAUQgCAHABABIAAABIABAAIgHAMIACgGIgEAFIAAAEQABACgFAGIgDADQABABgEAFIgGAIIAIgEIgLASQAAAAAAgBQAAAAgBAAQAAAAAAABQgBAAAAAAIgBADIgDACQgBADADACQABADgUAQQAAAAABAAQAAAAAAAAQAAAAAAAAQgBAAAAABIADgCIgKAGQAAACgFAEIgJAFIgBAAIABgCIgHADQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBABQgBgCgIAEQgKAGgFABIgOADQgLABgCABIAAgBIgHACIABAAIgCAAIAAABIABAAIAAAAQgDgBgEAAIgBAAIgDAAIAEgBIgQgCIgKgDQACgBAOgCIACABIADgBQAAAAABgBQAAAAAAAAQAAAAAAAAQAAgBgBAAQAFABACgCIACgDIAEABIAJgDIACABIAJgFIgGAAIADgBQASgCAIgHIAFgEIgBABIATgPQAKgIAIgMIgGAEQAKgOAHgOIAIgUIAFgLQACgGACgOIAAgUQAAgJgCgLIgDgTQgKgngfgbQgcgZgpgJIABAAIgPgEQgFgBgJABIAAgBIgFAAQgYAAgSAJQgCAAgHACIgKAEQghANgVAdQgXAfgFAjIgCAGIABAAIgCAPIABANQAAAGACAJIABANIADAGQAJAYAKAOQANATAQANQASAQALAGQAVAJAWACQAFAEALAGIAFAKIgWAIg");
	this.shape.setTransform(30.3,17.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B32538").s().p("AAAAEIAAgHIABAAIgBAIg");
	this.shape_1.setTransform(47.4,21.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B32538").s().p("AEeCMIABgCIgBgDQgBAAAAAAQAAgBAAAAQAAAAgBAAQAAABAAAAQABgFgBgBIgDgDIABgDIgCgJIABgBIgDgJIAAAEIgBgCIABAAIgBgRIgCgJIgDgFIAAABIgHgVQgDgLgHgLIAAAHQgHgPgIgMQgRgXAAgCQgJgOgRgQIgbgYQgGgFgYgRIgRgHQgJgFgHgCIgkgKIgSgEIgSgDIABAAQgTgDgIACIAAgBIgGAAQgbABgLAEIgTACQg8AKg5AwIgFADIACABQgNAJgIAKQgHAJgLAKIgCAGIgVAhIgQAlIgMAfIgFApIgJAQIgKAFIgIgTIABgNQABgLABgDIAAAAQABAAABgJQAAgIACgCQABgDAAgGIABgHQADgCAAgEIgBgFQAAgFADgBIAFgQIgBAAIAPgfQAKgRAIgJQAAAEABgFIAEgGIAAAAIACgHQABgEAEgCQAAABABAAQAAAAAAgBQAAAAABAAQAAgBAAgBQABAAAAAAQAAgBAAAAQAAAAAAAAQAAABAAAAQAGgJALgKIAJgIIAJgMIAAACIAEgEIgDgBQACAAAEgDQAAgBABgBQABAAAAAAQABgBAAAAQAAAAAAABIAAAAQABACAGgGQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAIADgDQAEgBAIgHQAIgEADgBIABgDQAFgBAKgIQAJgFAGAAIAJgGIAbgMQAUgGAEABIAOgCQAGgDAHgBQAAABAAAAQAAABAAAAQABAAAAAAQABAAABAAIAGgBQAAAAAAgBQABAAAAAAQAAAAABAAQABgBAAAAQABAAABAAQABAAABAAQAAAAABAAQAAAAAAgBIABACIAPAAIgCAAQAAABABAAQAAAAAAAAQABAAABAAQABAAABgBIACgCIgBACIADAAIgBABQAIABAAgDIADABIABgBIgBgBIAIACIgCABIAEABIAFgBIABgDIgEABIAIgCQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAEAAIADAAIABACIADgBQgDADAFACIAFABIgBgDIACADQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAIAAABQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAABAAIgCABIANACQAHAAAFAEIAAAAQAFACAEAAIAAAAIAGACIAAABIAFABIgBABQAFADAHABIgBgBQACAAADgEIADAAIADACQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABQAEAAAEAAQgGABAHAGIAJADIAHADIACAEQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABIADABIADACIAAgBIABABIAAAAQACADAEACIAFABQACgCADAGIACgBIATATQAAACAFADIAAgBQAKAMAMALIACABQgBAAAAAAQAAAAAAAAQAAABAAABQABABABABIAJAJIgBABIgRgTIgCABIADAGIADAAQAFAHAHAHQADAEACABIAAAAIAFAKIgEgEIACAFIADACQADABABAGIAAAEQACgBAEAOIABgIIAJAQQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAIACACIABADQACACADgCQADABAFAVIABgBIAAABIAAgDIABALQACAAABAGIADAIQAAAFgCgGIAAAHIABgBIABABIgBAEIAAAFIACAIQABAEAAACIAAANQgBAKABABIgBABIABAFIAAABIABAAIgCAHIABAAIgBACIAAgCIgHAXQgBgCgBgNg");
	this.shape_2.setTransform(29.8,52);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#B32538").s().p("AgCgCIABAAIAEAFg");
	this.shape_3.setTransform(54,48.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E0A2AA").s().p("AkABhIADgZIAFgZIAIgYIAHgRQAEgHAGgKQAggsAygcQAvgZA0gHQA0gHAzALQA0AMArAeQAzAhAcAwQAOAaAHAcIgDgKQgMgfgSgXQgSgWgagVQgQgMgIgEIgdgPQgkgOgZgGIgTgEIgrgEIgGAAQgUAAgZAFIgUAFIAEgBIgUAIIgVAKQgzAZgdAaIgNARIgKAKIgJALIgPAaQgPAcgDAjIgBgJIgEAXg");
	this.shape_4.setTransform(29.6,51.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,59.4,67.5);


(lib.ArtOnPathBrush_1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_1 = new lib.Group_1_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(13.2,13.9,1,1,0,0,0,13.2,13.4);
	this.instance_1.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_1_1, new cjs.Rectangle(0,0.5,26.7,26.9), null);


(lib.ArtOnPathBrush_0_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_1 = new lib.Group_0_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(15.2,14.7,1,1,0,0,0,14.6,14.7);
	this.instance_1.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_0_1, new cjs.Rectangle(0.6,0.4,29.2,28.6), null);


(lib.ArtOnPathBrush_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_1 = new lib.Group_2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(16,15.8,1,1,0,0,0,16,15.8);
	this.instance_1.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_2, new cjs.Rectangle(0.1,0,31.9,31.7), null);


(lib.greenai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.ArtOnPathBrush_1_1();
	this.instance.parent = this;
	this.instance.setTransform(29.9,19.5,1,1,0,0,0,13.2,13.9);

	this.instance_1 = new lib.ArtOnPathBrush_0_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(31.9,18.7,1,1,0,0,0,15.2,14.7);

	this.instance_2 = new lib.ArtOnPathBrush_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(28.9,17.6,1,1,0,0,0,16,15.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2B9447").s().p("AgUCxIgQgDQgJgBgFgDIgBAAQABgBgKgDQgKgCgBgCQgEgDgFgBIgJgDQgBgEgFgCQgKgDgCgCIgOgOIAAACIgOgPIgMgQQgMgTgEgPQABABAAAAQABABAAAAQAAgBgBAAQgBgBgBgBIgCgIIgBAAIgEgHQgDgEABgEQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAQgEgJAAgGIAAgsIAAACIABgGIgCABQABgBAAgGQABgGABABIAAABQACABACgKIgCABIABgEIAGgQQACgGAFgGIAAgEQAFgHAFgKQAGgLAGgDIAQgSQAFgHAMgKIANgIQAIgEAEAAIAQgHIAOgGQAAABAAAAQAAAAABAAQAAABABAAQABgBABAAQAGgCABABQAAgBAAAAQAAAAAAgBQABAAABAAQAAAAABAAQAFgBABgBIAAACIASgCIgCABQAAABAGgBIADgCIgBACIADgBIAAABQAIABAAgDIADACQAAAAABAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAEABQACABAEAAIgDAAIAFABQADABADgBIABgCIgFAAIAJgBIAAABIAFABQABABAAAAQABAAAAAAQABAAAAAAQAAAAABgBIAAACIAEAAQgEACAGACIAFACIgBgDIADADQABABAAAAQABAAAAAAQABAAABAAQAAAAABAAIgBACQABAAAAABQABAAAAAAQABAAAAAAQAAgBABAAIACABIgCAAIAPAFQAIADAEAEIAAABQAFAEAFACIgBgBIAHAEIgBACIAFADIgBAAQAHAHAFACIgBgBIAGgBIADACQABAAAAAAQAAAAABABQAAAAAAAAQABABAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAEADAEACQAAAAgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAACACAEIAIAIQADADACAEIAAAFQAAAAAAABQABAAAAABQABAAAAAAQABABAAAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIADAEQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAABIAAAAIAAABQABAEADAEIADAEQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIAAAEIADABIACAOIACARQgBABACAIIABgCIAAATIgBARIABADIgBAAIgCADIgBAQIgBgBIADgdIgCAAIgCAHIACACIgDAUQgCAHABABIAAABIABAAIgHAMIACgGIgEAFIAAAEQABACgFAGIgDADQABABgEAFIgGAIIAIgEIgLASQAAAAAAgBQAAAAgBAAQAAAAAAABQgBAAAAAAIgBADIgDACQgBADADACQABADgUAQQAAAAABAAQAAAAAAAAQAAAAAAAAQgBAAAAABIADgCIgKAGQAAACgFAEIgJAFIgBAAIABgCIgHADQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBABQgBgCgIAEQgKAGgFABIgOADQgLABgCABIAAgBIgHACIABAAIgCAAIAAABIABAAIAAAAQgDgBgEAAIgBAAIgDAAIAEgBIgQgCIgKgDQACgBAOgCIACABIADgBQAAAAABgBQAAAAAAAAQAAAAAAAAQAAgBgBAAQAFABACgCIACgDIAEABIAJgDIACABIAJgFIgGAAIADgBQASgCAIgHIAFgEIgBABIATgPQAKgIAIgMIgGAEQAKgOAHgOIAIgUIAFgLQACgGACgOIAAgUQAAgJgCgLIgDgTQgKgngfgbQgcgZgpgJIABAAIgPgEQgFgBgJABIAAgBIgFAAQgYAAgSAJQgCAAgHACIgKAEQghANgVAdQgXAfgFAjIgCAGIABAAIgCAPIABANQAAAGACAJIABANIADAGQAJAYAKAOQANATAQANQASAQALAGQAVAJAWACQAFAEALAGIAFAKIgWAIg");
	this.shape.setTransform(30.3,17.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2B9447").s().p("AAAAEIAAgHIABAAIgBAIg");
	this.shape_1.setTransform(47.4,21.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2B9447").s().p("AEeCMIABgCIgBgDQgBAAAAAAQAAgBAAAAQAAAAgBAAQAAABAAAAQABgFgBgBIgDgDIABgDIgCgJIABgBIgDgJIAAAEIgBgCIABAAIgBgRIgCgJIgDgFIAAABIgHgVQgDgLgHgLIAAAHQgHgPgIgMQgRgXAAgCQgJgOgRgQIgbgYQgGgFgYgRIgRgHQgJgFgHgCIgkgKIgSgEIgSgDIABAAQgTgDgIACIAAgBIgGAAQgbABgLAEIgTACQg8AKg5AwIgFADIACABQgNAJgIAKQgHAJgLAKIgCAGIgVAhIgQAlIgMAfIgFApIgJAQIgKAFIgIgTIABgNQABgLABgDIAAAAQABAAABgJQAAgIACgCQABgDAAgGIABgHQADgCAAgEIgBgFQAAgFADgBIAFgQIgBAAIAPgfQAKgRAIgJQAAAEABgFIAEgGIAAAAIACgHQABgEAEgCQAAABABAAQAAAAAAgBQAAAAABAAQAAgBAAgBQABAAAAAAQAAgBAAAAQAAAAAAAAQAAABAAAAQAGgJALgKIAJgIIAJgMIAAACIAEgEIgDgBQACAAAEgDQAAgBABgBQABAAAAAAQABgBAAAAQAAAAAAABIAAAAQABACAGgGQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAIADgDQAEgBAIgHQAIgEADgBIABgDQAFgBAKgIQAJgFAGAAIAJgGIAbgMQAUgGAEABIAOgCQAGgDAHgBQAAABAAAAQAAABAAAAQABAAAAAAQABAAABAAIAGgBQAAAAAAgBQABAAAAAAQAAAAABAAQABgBAAAAQABAAABAAQABAAABAAQAAAAABAAQAAAAAAgBIABACIAPAAIgCAAQAAABABAAQAAAAAAAAQABAAABAAQABAAABgBIACgCIgBACIADAAIgBABQAIABAAgDIADABIABgBIgBgBIAIACIgCABIAEABIAFgBIABgDIgEABIAIgCQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAEAAIADAAIABACIADgBQgDADAFACIAFABIgBgDIACADQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAIAAABQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAABAAIgCABIANACQAHAAAFAEIAAAAQAFACAEAAIAAAAIAGACIAAABIAFABIgBABQAFADAHABIgBgBQACAAADgEIADAAIADACQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABQAEAAAEAAQgGABAHAGIAJADIAHADIACAEQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABIADABIADACIAAgBIABABIAAAAQACADAEACIAFABQACgCADAGIACgBIATATQAAACAFADIAAgBQAKAMAMALIACABQgBAAAAAAQAAAAAAAAQAAABAAABQABABABABIAJAJIgBABIgRgTIgCABIADAGIADAAQAFAHAHAHQADAEACABIAAAAIAFAKIgEgEIACAFIADACQADABABAGIAAAEQACgBAEAOIABgIIAJAQQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAIACACIABADQACACADgCQADABAFAVIABgBIAAABIAAgDIABALQACAAABAGIADAIQAAAFgCgGIAAAHIABgBIABABIgBAEIAAAFIACAIQABAEAAACIAAANQgBAKABABIgBABIABAFIAAABIABAAIgCAHIABAAIgBACIAAgCIgHAXQgBgCgBgNg");
	this.shape_2.setTransform(29.8,52);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2B9447").s().p("AgCgCIABAAIAEAFg");
	this.shape_3.setTransform(54,48.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#9DD4B2").s().p("AkABhIADgZIAFgZIAIgYIAHgRQAEgHAGgKQAggsAygcQAvgZA0gHQA0gHAzALQA0AMArAeQAzAhAcAwQAOAaAHAcIgDgKQgMgfgSgXQgSgWgagVQgQgMgIgEIgdgPQgkgOgZgGIgTgEIgrgEIgGAAQgUAAgZAFIgUAFIAEgBIgUAIIgVAKQgzAZgdAaIgNARIgKAKIgJALIgPAaQgPAcgDAjIgBgJIgEAXg");
	this.shape_4.setTransform(29.6,51.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,59.4,67.5);


(lib.ArtOnPathBrush_1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_2 = new lib.Group_1_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(13.2,13.9,1,1,0,0,0,13.2,13.4);
	this.instance_2.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_1_2, new cjs.Rectangle(0,0.5,26.7,26.9), null);


(lib.ArtOnPathBrush_0_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_2 = new lib.Group_0_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(15.2,14.7,1,1,0,0,0,14.6,14.7);
	this.instance_2.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_0_2, new cjs.Rectangle(0.6,0.4,29.2,28.6), null);


(lib.ArtOnPathBrush_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_2 = new lib.Group_3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(16,15.8,1,1,0,0,0,16,15.8);
	this.instance_2.alpha = 0.801;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.ArtOnPathBrush_3, new cjs.Rectangle(0.1,0,31.9,31.7), null);


(lib.blueai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.ArtOnPathBrush_1_2();
	this.instance.parent = this;
	this.instance.setTransform(29.9,19.5,1,1,0,0,0,13.2,13.9);

	this.instance_1 = new lib.ArtOnPathBrush_0_2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(31.9,18.7,1,1,0,0,0,15.2,14.7);

	this.instance_2 = new lib.ArtOnPathBrush_3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(28.9,17.6,1,1,0,0,0,16,15.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3073B9").s().p("AgUCxIgQgDQgJgBgFgDIgBAAQABgBgKgDQgKgCgBgCQgEgDgFgBIgJgDQgBgEgFgCQgKgDgCgCIgOgOIAAACIgOgPIgMgQQgMgTgEgPQABABAAAAQABABAAAAQAAgBgBAAQgBgBgBgBIgCgIIgBAAIgEgHQgDgEABgEQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAQgEgJAAgGIAAgsIAAACIABgGIgCABQABgBAAgGQABgGABABIAAABQACABACgKIgCABIABgEIAGgQQACgGAFgGIAAgEQAFgHAFgKQAGgLAGgDIAQgSQAFgHAMgKIANgIQAIgEAEAAIAQgHIAOgGQAAABAAAAQAAAAABAAQAAABABAAQABgBABAAQAGgCABABQAAgBAAAAQAAAAAAgBQABAAABAAQAAAAABAAQAFgBABgBIAAACIASgCIgCABQAAABAGgBIADgCIgBACIADgBIAAABQAIABAAgDIADACQAAAAABAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAEABQACABAEAAIgDAAIAFABQADABADgBIABgCIgFAAIAJgBIAAABIAFABQABABAAAAQABAAAAAAQABAAAAAAQAAAAABgBIAAACIAEAAQgEACAGACIAFACIgBgDIADADQABABAAAAQABAAAAAAQABAAABAAQAAAAABAAIgBACQABAAAAABQABAAAAAAQABAAAAAAQAAgBABAAIACABIgCAAIAPAFQAIADAEAEIAAABQAFAEAFACIgBgBIAHAEIgBACIAFADIgBAAQAHAHAFACIgBgBIAGgBIADACQABAAAAAAQAAAAABABQAAAAAAAAQABABAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAEADAEACQAAAAgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAACACAEIAIAIQADADACAEIAAAFQAAAAAAABQABAAAAABQABAAAAAAQABABAAAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIADAEQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAABIAAAAIAAABQABAEADAEIADAEQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIAAAEIADABIACAOIACARQgBABACAIIABgCIAAATIgBARIABADIgBAAIgCADIgBAQIgBgBIADgdIgCAAIgCAHIACACIgDAUQgCAHABABIAAABIABAAIgHAMIACgGIgEAFIAAAEQABACgFAGIgDADQABABgEAFIgGAIIAIgEIgLASQAAAAAAgBQAAAAgBAAQAAAAAAABQgBAAAAAAIgBADIgDACQgBADADACQABADgUAQQAAAAABAAQAAAAAAAAQAAAAAAAAQgBAAAAABIADgCIgKAGQAAACgFAEIgJAFIgBAAIABgCIgHADQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBABQgBgCgIAEQgKAGgFABIgOADQgLABgCABIAAgBIgHACIABAAIgCAAIAAABIABAAIAAAAQgDgBgEAAIgBAAIgDAAIAEgBIgQgCIgKgDQACgBAOgCIACABIADgBQAAAAABgBQAAAAAAAAQAAAAAAAAQAAgBgBAAQAFABACgCIACgDIAEABIAJgDIACABIAJgFIgGAAIADgBQASgCAIgHIAFgEIgBABIATgPQAKgIAIgMIgGAEQAKgOAHgOIAIgUIAFgLQACgGACgOIAAgUQAAgJgCgLIgDgTQgKgngfgbQgcgZgpgJIABAAIgPgEQgFgBgJABIAAgBIgFAAQgYAAgSAJQgCAAgHACIgKAEQghANgVAdQgXAfgFAjIgCAGIABAAIgCAPIABANQAAAGACAJIABANIADAGQAJAYAKAOQANATAQANQASAQALAGQAVAJAWACQAFAEALAGIAFAKIgWAIg");
	this.shape.setTransform(30.3,17.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3073B9").s().p("AAAAEIAAgHIABAAIgBAIg");
	this.shape_1.setTransform(47.4,21.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#3073B9").s().p("AEeCMIABgCIgBgDQgBAAAAAAQAAgBAAAAQAAAAgBAAQAAABAAAAQABgFgBgBIgDgDIABgDIgCgJIABgBIgDgJIAAAEIgBgCIABAAIgBgRIgCgJIgDgFIAAABIgHgVQgDgLgHgLIAAAHQgHgPgIgMQgRgXAAgCQgJgOgRgQIgbgYQgGgFgYgRIgRgHQgJgFgHgCIgkgKIgSgEIgSgDIABAAQgTgDgIACIAAgBIgGAAQgbABgLAEIgTACQg8AKg5AwIgFADIACABQgNAJgIAKQgHAJgLAKIgCAGIgVAhIgQAlIgMAfIgFApIgJAQIgKAFIgIgTIABgNQABgLABgDIAAAAQABAAABgJQAAgIACgCQABgDAAgGIABgHQADgCAAgEIgBgFQAAgFADgBIAFgQIgBAAIAPgfQAKgRAIgJQAAAEABgFIAEgGIAAAAIACgHQABgEAEgCQAAABABAAQAAAAAAgBQAAAAABAAQAAgBAAgBQABAAAAAAQAAgBAAAAQAAAAAAAAQAAABAAAAQAGgJALgKIAJgIIAJgMIAAACIAEgEIgDgBQACAAAEgDQAAgBABgBQABAAAAAAQABgBAAAAQAAAAAAABIAAAAQABACAGgGQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAIADgDQAEgBAIgHQAIgEADgBIABgDQAFgBAKgIQAJgFAGAAIAJgGIAbgMQAUgGAEABIAOgCQAGgDAHgBQAAABAAAAQAAABAAAAQABAAAAAAQABAAABAAIAGgBQAAAAAAgBQABAAAAAAQAAAAABAAQABgBAAAAQABAAABAAQABAAABAAQAAAAABAAQAAAAAAgBIABACIAPAAIgCAAQAAABABAAQAAAAAAAAQABAAABAAQABAAABgBIACgCIgBACIADAAIgBABQAIABAAgDIADABIABgBIgBgBIAIACIgCABIAEABIAFgBIABgDIgEABIAIgCQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAEAAIADAAIABACIADgBQgDADAFACIAFABIgBgDIACADQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAIAAABQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAABAAIgCABIANACQAHAAAFAEIAAAAQAFACAEAAIAAAAIAGACIAAABIAFABIgBABQAFADAHABIgBgBQACAAADgEIADAAIADACQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABQAEAAAEAAQgGABAHAGIAJADIAHADIACAEQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABIADABIADACIAAgBIABABIAAAAQACADAEACIAFABQACgCADAGIACgBIATATQAAACAFADIAAgBQAKAMAMALIACABQgBAAAAAAQAAAAAAAAQAAABAAABQABABABABIAJAJIgBABIgRgTIgCABIADAGIADAAQAFAHAHAHQADAEACABIAAAAIAFAKIgEgEIACAFIADACQADABABAGIAAAEQACgBAEAOIABgIIAJAQQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAIACACIABADQACACADgCQADABAFAVIABgBIAAABIAAgDIABALQACAAABAGIADAIQAAAFgCgGIAAAHIABgBIABABIgBAEIAAAFIACAIQABAEAAACIAAANQgBAKABABIgBABIABAFIAAABIABAAIgCAHIABAAIgBACIAAgCIgHAXQgBgCgBgNg");
	this.shape_2.setTransform(29.8,52);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#3073B9").s().p("AgCgCIABAAIAEAFg");
	this.shape_3.setTransform(54,48.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#A5C6E3").s().p("AkABhIADgZIAFgZIAIgYIAHgRQAEgHAGgKQAggsAygcQAvgZA0gHQA0gHAzALQA0AMArAeQAzAhAcAwQAOAaAHAcIgDgKQgMgfgSgXQgSgWgagVQgQgMgIgEIgdgPQgkgOgZgGIgTgEIgrgEIgGAAQgUAAgZAFIgUAFIAEgBIgUAIIgVAKQgzAZgdAaIgNARIgKAKIgJALIgPAaQgPAcgDAjIgBgJIgEAXg");
	this.shape_4.setTransform(29.6,51.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,59.4,67.5);


// stage content:
(lib.A1index = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Blue Ex (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("ALnQHQgLgMAAgQQAAgQALgMQAMgLAQAAQARAAALALQAMAMAAAQQAAAQgMAMQgLAMgRAAQgQAAgMgMg");
	var mask_graphics_1 = new cjs.Graphics().p("AhQBQQggghAAgvQAAguAgghQAighAuAAQAvAAAhAhQAhAhAAAuQAAAvghAhQghAhgvAAQguAAgighg");
	var mask_graphics_2 = new cjs.Graphics().p("AiDCEQg3g2AAhOQAAhNA3g2QA2g2BNgBQBOABA2A2QA3A2AABNQAABOg3A2Qg2A3hOAAQhNAAg2g3g");
	var mask_graphics_3 = new cjs.Graphics().p("AHMQvQhMhMAAhtQAAhsBMhMQBLhMBtAAQBtAABMBMQBLBMAABsQAABthLBMQhMBLhtAAQhtAAhLhLg");
	var mask_graphics_4 = new cjs.Graphics().p("AjAElQgrgSgngUQgigmAKiFIAAgBQALiTAXgzQABgUAcgdIAOgOIBJhDQAfgyA+gaIAHgDQA6gXA/ALQBFANAzAzIAEADQAwAxAMBBQAOAkAVBnQAHAyACA4QADBWgYA7QgIA1gaARQgvAfiDAEIgMAAQh3AAiBgvg");
	var mask_graphics_5 = new cjs.Graphics().p("AjZGWQg7gIg9gLQglgTATjEQAWjUABglQgLgVAngpIASgTQBFhAAMgbQAPhPBFgzIAIgFQBCguBSAGQBZAGA/A/IAFAFQA7A9AGBVIAxCvQAPA8AQBJQAYBygBBHQAIBSgVARQglAdi/AIIg0ABQh8AAiggUg");
	var mask_graphics_6 = new cjs.Graphics().p("ACSR3QAhkUgXgXQgagbBMhIQBZhSAAghQAAhtBLhMQBMhLBtAAQBtAABLBLQBMBMAABtQAAATBzFhQBqFCgeAeQgxAxshAAQgnAAAdkEg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:81.1,y:104.3}).wait(1).to({graphics:mask_graphics_1,x:157.1,y:204.1}).wait(1).to({graphics:mask_graphics_2,x:156,y:203.7}).wait(1).to({graphics:mask_graphics_3,x:90.4,y:114.6}).wait(1).to({graphics:mask_graphics_4,x:154.5,y:212}).wait(1).to({graphics:mask_graphics_5,x:155.8,y:220.3}).wait(1).to({graphics:mask_graphics_6,x:101.3,y:140.3}).wait(1).to({graphics:null,x:0,y:0}).wait(47));

	// Blue Ex
	this.instance = new lib.blueai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(155.7,226.9,1.331,1.329,0,0,0,30.5,34.4);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(54));

	// Blue Caption (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("Ag6B5IAAjxIB1AAIAADxg");
	var mask_1_graphics_6 = new cjs.Graphics().p("AkHB5IAAjxIIPAAIAADxg");
	var mask_1_graphics_7 = new cjs.Graphics().p("AlZB5IAAjxIKzAAIAADxg");
	var mask_1_graphics_8 = new cjs.Graphics().p("AmsB5IAAjxINZAAIAADxg");
	var mask_1_graphics_9 = new cjs.Graphics().p("An+B5IAAjxIP9AAIAADxg");
	var mask_1_graphics_10 = new cjs.Graphics().p("ApQB5IAAjxIShAAIAADxg");
	var mask_1_graphics_11 = new cjs.Graphics().p("AqiB5IAAjxIVFAAIAADxg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:96.2,y:283.9}).wait(6).to({graphics:mask_1_graphics_6,x:117.2,y:283.9}).wait(1).to({graphics:mask_1_graphics_7,x:125.6,y:283.9}).wait(1).to({graphics:mask_1_graphics_8,x:134,y:283.9}).wait(1).to({graphics:mask_1_graphics_9,x:142.4,y:283.9}).wait(1).to({graphics:mask_1_graphics_10,x:150.8,y:283.9}).wait(1).to({graphics:mask_1_graphics_11,x:159.2,y:283.9}).wait(43));

	// Layer_7
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAEBMQgNAAgJgRQgHgNgDgcQgCgRAAgaIAAgCIACAAQgKgBAAgHQAAgHAKgBIgCAAIAAgHQAAgXADAAQADgCADAAQAIACAAAGIAAATIAAADIgDACIABAAIACAAIAmgBQAIABAAAGQAAAIgLAAIgjABIAAADQAAAiAGAgQAFATAHAAQAIAAANgNIAFgBQAIACAAAGQAAAGgTAMQgIAEgHAAgAgNgrgAgPgrIgBAAIADgCIAAACgAgNgtIAAAAIAAACgAgNgtg");
	this.shape.setTransform(186.8,286.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgJBBQgUAAgHgbQgCgLAAgMQAAgiAMgZQALgUAQAAQAQAAASAUQACAAACBiQgCAIgHAAQgIAAAAgMIAAgGIACgFIABgEQAAgEgEAAIABANQgJAPgMAEIgJACgAgSgMQgDAPAAANQABAcAIAFIAEABQAUAAAGg9IACgZQgMgNgHAAQgMAAgHAlgAAWAsIgBgNQAEAAAAAEIgBAEIgCAFg");
	this.shape_1.setTransform(178.2,287.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgjA5IgBhxQACgIAHAAQAFAAACAGIgDACIAEAAIgBgCQAKgFAMAAQAOAAANAOQAIAMAAAEQgBAIgIAAQgGAAgFgLQgHgLgIAAQgOAAgGAJIgBAAIABBfQgCAIgHAAQgIgCAAgGgAgTg3IAAgBIAAAAIAAAAIAAABIAAgBIAAABgAgTg4gAgXg4IADgCIABACgAgUg6IAAAAg");
	this.shape_2.setTransform(170.2,287.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgiAlQgEgLAAgQQAAg2AngQQAMgEALAAIACAAQANAAAAAIQgCAIgGAAIgGgBQgeABgKAZQgGANAAAUQAAAoAaAAQAIAAAOgFQAJACAAAGQAAAIgWADIgJABQgcAAgLgcg");
	this.shape_3.setTransform(161.9,287.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgfAvQgHgOAAgfQAAgXAJgWQAFgMAKgFQAKgEAFAAIACAAQAUAAAKATQAGAOAAAfQAAAsgMAKQgMALgPAAQgVAAgKgSgAgLgqQgEAGgDAMQgDASAAAJQAAAkAKAHQAFADAGAAQALAAAGgJQAFgLAAgeQAAgjgIgIQgEgEgIAAQgIAAgFAGg");
	this.shape_4.setTransform(153.3,287.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AApA5QAAhOgCAAQgDgOgCgDQgFgKgLAAQgHAAgFALQAFARAAASIAAAFIAAA2QgBAIgHAAQgGAAgCgIIAAg1IAAgFQAAgegJgMQgHgFgHAAQgHAAgFAMIABBdQgCAHgHAAQgIgCAAgGIgBhwQABgIAHAAQAFAAACAEIgDADIAEAAIABACIAAgCIgBAAIgBgDIABADIgEAAIADgDQAGgEAIAAQAMAAAMAJIACACQAHgLANAAQAOAAAMALQAOAOAAAsIAAA0QgBAIgHAAQgHAAgCgIgAAAgzIgCgCIACACIgEAAIACgCIgCACIAEAAgAAAgzgAgpg5IABAAIAAACIgBgCgAgpg5g");
	this.shape_5.setTransform(143,287.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgdAsQgJgSAAgTIAAgHQAAgSAJgXQALgXAPAAIADAAQAOAAANAQQAJAOADAQIAAAEIAAABQAAAIgIACQgQADgfABIgFAAIAAAFQAAAVAKAOQAGAIAIAAQAJAAALgMIADgBQAIAAABAIQAAAIgUAKQgFADgIAAQgTAAgMgVgAgXgOIADAAIAAAAIAqgDIgBgBQgCgKgCgEQgIgQgKAAIgBAAQgJAAgHAeIgCAEg");
	this.shape_6.setTransform(132.5,287.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgVBoQgRAAgGgJQgDgOAAhQQAAhnAHAAQACgBAGAAQAZAAAWASQAMAMAEAHQARAdAAApQAABJgrAVQgNAGgKAAgAgegmIAAAnIABBWIAIACIADAAQAKAAALgHQAcgTAAg7QAAghgNgbIgJgMQgLgMgIgDQgGgDgMgBQgBAIgBApg");
	this.shape_7.setTransform(123.1,283.4);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(54));

	// Red Ex (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_11 = new cjs.Graphics().p("AZUQFQgMgLAAgRQAAgQAMgMQALgLAQAAQARAAALALQAMAMAAAQQAAARgMALQgLAMgRAAQgQAAgLgMg");
	var mask_2_graphics_12 = new cjs.Graphics().p("AhPBQQghghAAgvQAAgvAhggQAhghAuAAQAwAAAgAhQAhAgAAAvQAAAvghAhQggAhgwAAQguAAghghg");
	var mask_2_graphics_13 = new cjs.Graphics().p("AiECFQg2g3AAhOQAAhNA2g2QA3g3BNAAQBOAAA2A3QA3A2AABNQAABOg3A3Qg2A2hOAAQhNAAg3g2g");
	var mask_2_graphics_14 = new cjs.Graphics().p("AVFQvQhMhMAAhtQAAhsBMhMQBMhMBsAAQBtAABMBMQBMBMAABsQAABthMBMQhMBLhtAAQhsAAhMhLg");
	var mask_2_graphics_15 = new cjs.Graphics().p("AjEEvQgngQglgRQglgoAKiSQALigAbg0QAAgQAWgZIAVgUIBIhCQAfgxA9gaIAFgCQA6gXA/AKQBDAMAyAxIAJAJQAsAuAMA8QAQAnAWBxQAHAyACA2QADBagYA+QgKA6gaASQgvAdiCAFIgOAAQh4AAiBgug");
	var mask_2_graphics_16 = new cjs.Graphics().p("AjhGqIhvgQQgmgUATjaQAWjnACglQgJgSAegjQAKgNAPgOQBGg/ALgbQAPhPBFgzIAGgFQBCguBTAGQBYAFA/A/IALALQA1A7AGBQIA0DBQAOA7APBJQAYB3gCBMQAJBagWARQgkAdi/AJQghABgjAAQh6AAiagRg");
	var mask_2_graphics_17 = new cjs.Graphics().p("AQDR1QAhkugXgXQgagbBMhIQBZhSAAghQAAhtBLhMQBMhLBtAAQBtAABLBLQBMBMAABtQAAATBzF4QBqFcgeAeQgxAxshAHQgnAAAdkig");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(11).to({graphics:mask_2_graphics_11,x:168.7,y:104.1}).wait(1).to({graphics:mask_2_graphics_12,x:333.2,y:203.9}).wait(1).to({graphics:mask_2_graphics_13,x:333,y:203.6}).wait(1).to({graphics:mask_2_graphics_14,x:179.4,y:114.6}).wait(1).to({graphics:mask_2_graphics_15,x:331.8,y:212.9}).wait(1).to({graphics:mask_2_graphics_16,x:332.5,y:222}).wait(1).to({graphics:mask_2_graphics_17,x:189.4,y:143.1}).wait(37));

	// Red Ex
	this.instance_1 = new lib.redai("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(333.3,226.5,1.331,1.329,0,0,0,30.6,34.1);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).wait(43));

	// Red Caption (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_11 = new cjs.Graphics().p("Ag6B5IAAjxIB1AAIAADxg");
	var mask_3_graphics_17 = new cjs.Graphics().p("AjuCRIAAkhIHdAAIAAEhg");
	var mask_3_graphics_18 = new cjs.Graphics().p("AkqCPIAAkdIJVAAIAAEdg");
	var mask_3_graphics_19 = new cjs.Graphics().p("AlmCOIAAkbILNAAIAAEbg");
	var mask_3_graphics_20 = new cjs.Graphics().p("AmjCMIAAkXINGAAIAAEXg");
	var mask_3_graphics_21 = new cjs.Graphics().p("AneCKIAAkTIO9AAIAAETg");
	var mask_3_graphics_22 = new cjs.Graphics().p("AobCJIAAkRIQ2AAIAAERg");
	var mask_3_graphics_23 = new cjs.Graphics().p("ApXCHIAAkNISvAAIAAENg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(11).to({graphics:mask_3_graphics_11,x:96.2,y:283.9}).wait(6).to({graphics:mask_3_graphics_17,x:293.1,y:286.2}).wait(1).to({graphics:mask_3_graphics_18,x:299.6,y:285.9}).wait(1).to({graphics:mask_3_graphics_19,x:306.1,y:285.6}).wait(1).to({graphics:mask_3_graphics_20,x:312.6,y:285.3}).wait(1).to({graphics:mask_3_graphics_21,x:319.1,y:285}).wait(1).to({graphics:mask_3_graphics_22,x:325.6,y:284.7}).wait(1).to({graphics:mask_3_graphics_23,x:332.1,y:284.4}).wait(31));

	// Layer_14 copy
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AglA5IgBhwQABgIAHAAQAGAAABADIgDADIAEAAIgBgDIABADIgEAAIADgDQAHgEAIAAQARAAAPARQAPAWAAAqIAAABQAAAYgCARQgEAFgFAAQgIgCAAgGQACgSAAgUQAAgggJgUQgGgLgKgDIgFAAQgHAAgGAMIABBeQgCAHgHAAQgIgCAAgGgAgWg5g");
	this.shape_8.setTransform(368.5,287.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AgJBBQgUAAgHgbQgCgLAAgMQAAgiAMgZQALgUAQAAQAQAAASAUQACAAACBiQgCAIgHAAQgIAAAAgMIAAgGIACgFIABgEQAAgEgEAAIABANQgJAPgMAEIgJACgAgSgMQgDAPAAANQABAcAIAFIAEABQAUAAAGg9IACgZQgMgNgHAAQgMAAgHAlgAAWAsIgBgNQAEAAAAAEIgBAEIgCAFg");
	this.shape_9.setTransform(359.9,287.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AgiAlQgEgLAAgQQAAg2AngQQAMgEALAAIACAAQANAAAAAIQgCAIgGAAIgGgBQgeABgKAZQgGANAAAUQAAAoAaAAQAIAAAOgFQAJACAAAGQAAAIgWADIgJABQgcAAgLgcg");
	this.shape_10.setTransform(351.5,287.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgHBDIAAhxQACgIAGAAQAIABAAAHIAABxQgBAIgHgBQgIgCAAgFgAgIhAQACgKAGABQAHAAACAIQgCAJgHAAQgIgCAAgGg");
	this.shape_11.setTransform(345.6,286.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AgIBgIABjAQACgHAGAAQAJABAAAGIgCDBQgCAHgGAAQgJgCABgGg");
	this.shape_12.setTransform(342.8,283.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AgRBoQgRgCAAgCQgEAAAAhRIAAgJIAAhkQAAgNAEAAIAFAAQAGAAADAGIgBANIAABCIgEABIAEAAIAAgBQALgEAJAAIABAAQAaAAAKAcQADAMAAAQQAAAzggAOQgJAFgLAAgAgVgBIAAADQAABWgBAAIAHABIABAAQAYAAAIgbQAEgNAAgPQAAgegMgHQgDgDgIAAQgJAAgLAFgAgZgRIAEgBIAAABg");
	this.shape_13.setTransform(337.2,283.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgJBBQgJAAgJgLQgLgOAAgiIAAgCQAAgcAHgjQAEgFAEAAQAHAAACAIQgHAjAAAaQAAAmALAFIACABIABAAQAPAAAFglQADgMAAgXIgCggQACgHAHAAQAJAAAAAQIAHBlQgCAIgHAAQgIAAAAgKIgBgHQADgGACgFIgGgCIABANIgBgNIAGACQgCAFgDAGQgDAFgGAGQgKAIgIAAg");
	this.shape_14.setTransform(328.7,287.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AgkBKIgCh5QAAgkAFAAQADgDAJAAIABAAQAVAAATARQATASAAAgQAAArgkAQQgMAFgLAAIAAgDIAAADIABAiQAAAFgIADQgJAAAAgNgAgWhGIABAAIABAAIgBAYIABBMQAVAAANgTQAIgLAAgTQAAgkgZgLQgJgEgIAAIAAAAg");
	this.shape_15.setTransform(320.2,289.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AgdAsQgJgSAAgTIAAgHQAAgSAJgXQALgXAPAAIADAAQAOAAANAQQAJAOADAQIAAAEIAAABQAAAIgIACQgQADgfABIgFAAIAAAFQAAAVAKAOQAGAIAIAAQAJAAALgMIADgBQAIAAABAIQAAAIgUAKQgFADgIAAQgTAAgMgVgAgXgOIADAAIABAAIApgDIgBgBQgCgKgCgEQgIgQgKAAIgBAAQgJAAgHAeIgBAEg");
	this.shape_16.setTransform(311.7,287.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgrBbQgDhRAAg+QAAgkADgHQAFgIAWAAQAZAAAUARQAOANADARIABANQAAAggVARQgSAQgVAEIgEABIgCgCIAAABIACABIA4BAIABADQgCAIgHAAQgFAAgIgLIgug0IAAgGIgFAAIAFAGIACA5QgCAIgGAAQgJAAAAgNgAgchXIgBAkIABBBQAGAAAVgIQAIgEAJgHQAOgOAAgYQAAgRgLgOQgPgOgVAAIgLABgAgcAngAghAhIAFAAIAAAGgAgRAbIAAAAgAgTAaIAAgBIACACIgCgBg");
	this.shape_17.setTransform(302.4,283.4);

	var maskedShapeInstanceList = [this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},11).wait(43));

	// Green Ex (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	var mask_4_graphics_23 = new cjs.Graphics().p("EAnEAQFQgLgLAAgRQAAgQALgMQAMgLAQAAQARAAALALQAMAMAAAQQAAARgMALQgLAMgRAAQgQAAgMgMg");
	var mask_4_graphics_24 = new cjs.Graphics().p("AhPBQQghghAAgvQAAgvAhggQAhghAuAAQAvAAAhAhQAhAgAAAvQAAAvghAhQghAhgvAAQguAAghghg");
	var mask_4_graphics_25 = new cjs.Graphics().p("AiECFQg2g3AAhOQAAhNA2g2QA3g3BNAAQBOAAA2A3QA3A2AABNQAABOg3A3Qg2A2hOAAQhNAAg3g2g");
	var mask_4_graphics_26 = new cjs.Graphics().p("EAi+AQvQhMhMAAhtQAAhsBMhMQBMhMBsAAQBtAABMBMQBMBMAABsQAABthMBMQhMBLhtAAQhsAAhMhLg");
	var mask_4_graphics_27 = new cjs.Graphics().p("AjEEvQgngQgkgRQgmgoAKiSQALigAbg0QABgQAVgZIAVgUIBIhCQAfgxA9gaIAGgCQA5gXA/AKQBDAMAzAxIAJAJQArAuANA8QAPAnAWBxQAHAyACA2QADBagYA+QgJA6gbASQguAdiDAFIgOAAQh4AAiBgug");
	var mask_4_graphics_28 = new cjs.Graphics().p("AjhGqIhvgQQgmgUAUjaQAWjnACglQgKgSAegjQALgNAPgOQBFg/ALgbQAQhPBEgzIAGgFQBDguBSAGQBYAFA/A/IALALQA1A7AGBQQAIAaAtCnQAOA7AOBJQAZB3gCBMQAIBagVARQglAdi/AJQghABgjAAQh5AAibgRg");
	var mask_4_graphics_29 = new cjs.Graphics().p("Ad9R1QAhkugXgXQgbgbBMhIQBZhSAAghQAAhtBMhMQBLhLBtAAQBtAABMBLQBLBMAABtQAAATB0F4QBpFcgeAeQgxAxsgAHQgoAAAekig");

	this.timeline.addTween(cjs.Tween.get(mask_4).to({graphics:null,x:0,y:0}).wait(23).to({graphics:mask_4_graphics_23,x:256.8,y:104.1}).wait(1).to({graphics:mask_4_graphics_24,x:509.9,y:203.9}).wait(1).to({graphics:mask_4_graphics_25,x:510.2,y:203.6}).wait(1).to({graphics:mask_4_graphics_26,x:268.3,y:114.6}).wait(1).to({graphics:mask_4_graphics_27,x:509.6,y:212.9}).wait(1).to({graphics:mask_4_graphics_28,x:510.3,y:222}).wait(1).to({graphics:mask_4_graphics_29,x:278.3,y:143.1}).wait(25));

	// Green Ex
	this.instance_2 = new lib.greenai("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(509.2,226.9,1.331,1.329,0,0,0,30.4,34.4);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(23).to({_off:false},0).wait(31));

	// Green Caption (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	var mask_5_graphics_23 = new cjs.Graphics().p("Ag6B5IAAjxIB1AAIAADxg");
	var mask_5_graphics_29 = new cjs.Graphics().p("Ag6CWIAAkrIB1AAIAAErg");
	var mask_5_graphics_30 = new cjs.Graphics().p("AjaCSIAAkjIG1AAIAAEjg");
	var mask_5_graphics_31 = new cjs.Graphics().p("Al7COIAAkcIL3AAIAAEcg");
	var mask_5_graphics_32 = new cjs.Graphics().p("Am7CNIAAkZIN3AAIAAEZg");
	var mask_5_graphics_33 = new cjs.Graphics().p("An7CMIAAkWIP3AAIAAEWg");
	var mask_5_graphics_34 = new cjs.Graphics().p("Ao7CKIAAkTIR3AAIAAETg");
	var mask_5_graphics_35 = new cjs.Graphics().p("Ap7CIIAAkPIT3AAIAAEPg");
	var mask_5_graphics_36 = new cjs.Graphics().p("Aq7CHIAAkNIV3AAIAAENg");

	this.timeline.addTween(cjs.Tween.get(mask_5).to({graphics:null,x:0,y:0}).wait(23).to({graphics:mask_5_graphics_23,x:96.2,y:283.9}).wait(6).to({graphics:mask_5_graphics_29,x:436,y:288.5}).wait(1).to({graphics:mask_5_graphics_30,x:454.3,y:287.7}).wait(1).to({graphics:mask_5_graphics_31,x:472.6,y:286.9}).wait(1).to({graphics:mask_5_graphics_32,x:479.9,y:286.6}).wait(1).to({graphics:mask_5_graphics_33,x:487.2,y:286.3}).wait(1).to({graphics:mask_5_graphics_34,x:494.6,y:286}).wait(1).to({graphics:mask_5_graphics_35,x:501.9,y:285.6}).wait(1).to({graphics:mask_5_graphics_36,x:509.2,y:285.3}).wait(18));

	// Layer_14 copy 2
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AgdAsQgJgSAAgTIAAgHQAAgSAJgXQALgXAPAAIADAAQAOAAANAQQAJAOADAQIAAAEIAAABQAAAIgIACQgQADgfABIgFAAIAAAFQAAAVAKAOQAGAIAIAAQAJAAALgMIADgBQAIAAABAIQAAAIgUAKQgFADgIAAQgTAAgMgVgAgXgOIADAAIAAAAIAqgDIgBgBQgCgKgCgEQgIgQgKAAIgBAAQgJAAgHAeIgCAEg");
	this.shape_18.setTransform(552.5,287.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AgjA5IgBhxQACgIAGAAQAGAAACAGIgDACIAEAAIgBgCQAKgFANAAQANAAANAOQAIAMAAAEQgCAIgGAAQgHAAgFgLQgGgLgJAAQgOAAgHAJIAAAAIABBfQgCAIgHAAQgIgCAAgGgAgTg3IAAgBIAAAAIAAAAIAAABIAAgBIAAABgAgTg4gAgXg4IADgCIABACgAgUg6IAAAAg");
	this.shape_19.setTransform(544.4,287.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AgJBBQgUAAgHgbQgCgLAAgMQAAgiAMgZQALgUAQAAQAQAAASAUQACAAACBiQgCAIgHAAQgIAAAAgMIgBgGIADgFIABgEQAAgEgEAAIAAANQgIAPgMAEIgJACgAgSgMQgDAPAAANQABAcAIAFIAEABQAUAAAGg9IACgZQgMgNgHAAQgMAAgHAlgAAVAsIAAgNQAEAAAAAEIgBAEIgDAFg");
	this.shape_20.setTransform(536,287.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AgiAlQgEgLAAgQQAAg2AngQQAMgEALAAIACAAQANAAAAAIQgCAIgGAAIgGgBQgeABgKAZQgGANAAAUQAAAoAaAAQAIAAAOgFQAJACAAAGQAAAIgWADIgJABQgcAAgLgcg");
	this.shape_21.setTransform(527.6,287.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AAEBMQgNAAgJgRQgHgNgDgcQgCgRAAgaIAAgCIACAAQgKgBAAgHQAAgHAKgBIgCAAIAAgHQAAgXADAAQADgCADAAQAIACAAAGIAAATIAAADIgDACIABAAIACAAIAmgBQAIABAAAGQAAAIgLAAIgjABIAAADQAAAiAGAgQAFATAHAAQAIAAANgNIAFgBQAIACAAAGQAAAGgTAMQgIAEgHAAgAgNgrgAgPgrIgBAAIADgCIAAACgAgNgtIAAAAIAAACgAgNgtg");
	this.shape_22.setTransform(512.1,286.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AgIAMIAAgXQACgJAGABQAHAAABAIIAAAYQgBAIgHgBQgGAAgCgIg");
	this.shape_23.setTransform(506.6,275);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AglA5IgBhwQABgIAHAAQAGAAACADIgEADIAEAAIAAgDIAAADIgEAAIAEgDQAGgEAIAAQARAAAPARQAPAWAAAqIAAABQAAAYgCARQgEAFgFAAQgIgCAAgGQACgSAAgUQAAgggJgUQgGgLgKgDIgFAAQgHAAgGAMIABBeQgCAHgHAAQgIgCAAgGgAgWg5g");
	this.shape_24.setTransform(501,287.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AgFBBQgbAAAAgIIgBgCQAAgGAJgCQAIACAMAAIACAAQAKAAAJgFQAFgEAAgLQAAgPgQgHIgYgLQgUgKAAgRIAAAAQAAgLAIgKQALgMAVAAIADAAQAZACAAAGIAAACQAAAHgJABQgLgCgGAAIgBAAQgYAAAAARQAAAKARAHQARAHAKAHQAQALAAASIAAABQAAAXgWAIQgMAEgGAAg");
	this.shape_25.setTransform(492.5,287.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AgdAsQgJgSAAgTIAAgHQAAgSAJgXQALgXAPAAIADAAQAOAAANAQQAJAOADAQIAAAEIAAABQAAAIgIACQgQADgfABIgFAAIAAAFQAAAVAKAOQAGAIAIAAQAJAAALgMIADgBQAIAAABAIQAAAIgUAKQgFADgIAAQgTAAgMgVgAgXgOIADAAIAAAAIAqgDIgBgBQgCgKgCgEQgIgQgKAAIgBAAQgJAAgHAeIgCAEg");
	this.shape_26.setTransform(484,287.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AgfAvQgHgOAAgfQAAgXAJgWQAFgMAKgFQAKgEAFAAIACAAQAUAAAKATQAGAOAAAfQAAAsgMAKQgMALgPAAQgVAAgKgSgAgLgqQgEAGgDAMQgDASAAAJQAAAkAKAHQAFADAGAAQALAAAGgJQAFgLAAgeQAAgjgIgIQgEgEgIAAQgIAAgFAGg");
	this.shape_27.setTransform(475.4,287.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AgVBoQgRAAgGgJQgDgOAAhQQAAhnAHAAQACgBAGAAQAZAAAWASQAMAMAEAHQARAdAAApQAABJgrAVQgNAGgKAAgAgegmIAAAnIABBWIAIACIADAAQAKAAALgHQAcgTAAg7QAAghgNgbIgJgMQgLgMgIgDQgGgDgMgBQgBAIgBApg");
	this.shape_28.setTransform(466,283.4);

	var maskedShapeInstanceList = [this.shape_18,this.shape_19,this.shape_20,this.shape_21,this.shape_22,this.shape_23,this.shape_24,this.shape_25,this.shape_26,this.shape_27,this.shape_28];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18}]},23).wait(31));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(417.5,457.6,70.2,95.4);
// library properties:
lib.properties = {
	id: 'ACDAEE9789DB4B279F530FB87505F8F5',
	width: 651,
	height: 514,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['ACDAEE9789DB4B279F530FB87505F8F5'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;